spring:
  application:
    name: java-core-code
#  jackson:
#    serialization: true
#    deserialization: true
  datasource:
      url: jdbc:mysql://${MYSQL_HOST:localhost}:${MYSQL_PORT:3306}/${MYSQL_DATABASE:test}?autoReconnect=true&useUnicode=true&characterEncoding=UTF8&useSSL=false&tcpKeepAlive=true&autoReconnect=true
      username: ${MYSQL_USERNAME:root}
      password: ${MYSQL_PASSWORD:spring}
  redis:
    main:
      host: 127.0.0.1
      port: 6379

logging:
  file: ${user.home}/logs/java-core/test.log
  level.*: INFO
  level.io.terminus: INFO

