spring:
  application:
    name: java-core-code
  jackson:
    serialization: true
    deserialization: true

logging:
  file: ${user.home}/logs/java-core/test.log
  level.*: INFO
  level.io.terminus: INFO
